name: f4ture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  mime: ^2.0.0
  firebase_storage: ^13.0.5
  intl: ^0.20.2
  get_storage: ^2.1.1
  file_picker: ^10.3.8
  open_filex: ^4.7.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/